"""Unit tests for CP-5-03: field resolver (04 §5).

Contract: label → Answer Bank fingerprint (same key space as the brief path,
D-020) → resolve (06 §3) → type-match (select→option id, radio→value,
date→iso, checkbox→multi, number) → FieldFill {field_id, resolution,
filled, confidence, source, reason}. AC: type matching correct (08 CP-5-03).

Pure unit tests: no browser, no Playwright — TypedField built directly.
"""

import pytest

from src.copilot.answerbank.fingerprint import Question, fingerprint
from src.copilot.answerbank.resolver import ResolveContext
from src.copilot.browser.form.model import FieldKind, FieldOption, TypedField
from src.copilot.browser.resolver import resolve_field, resolve_fields
from src.copilot.constants import AnswerSource
from src.copilot.db.db import open_copilot_db


@pytest.fixture
def fresh_db(tmp_path, monkeypatch):
    cfg = tmp_path / "copilot.yaml"
    cfg.write_text(f"copilot:\n  db_path: \"{tmp_path / 't' / 'copilot.db'}\"\n")
    monkeypatch.setenv("COPILOT_CONFIG", str(cfg))
    conn = open_copilot_db()
    yield conn
    conn.close()


def field(
    kind,
    label,
    *,
    options=(),
    name="n",
    required=False,
    field_id="f1",
    confidence=1.0,
):
    return TypedField(
        field_id=field_id,
        kind=kind,
        label=label,
        name=name,
        options=tuple(FieldOption(value=v, label=lb) for v, lb in options),
        required=required,
        page=0,
        confidence=confidence,
    )


def store_answer(conn, label, semantic, profile_id="ai", **overrides):
    row = {
        "question_fp": fingerprint(Question(label=label)),
        "profile_id": profile_id,
        "source": "manual",
        "semantic_answer": semantic,
        "serialized_answer": semantic,
        "confidence": 1.0,
        "status": "confirmed",
        "reason": "human",
    }
    row.update(overrides)
    conn.execute(
        "INSERT INTO copilot_answers (question_fp, profile_id, source, "
        "semantic_answer, serialized_answer, confidence, status, reason) "
        "VALUES (:question_fp, :profile_id, :source, :semantic_answer, "
        ":serialized_answer, :confidence, :status, :reason)",
        row,
    )
    conn.commit()


def resolve_hybrid(**overrides):
    result = {
        "status": "resolved",
        "source": "llm",
        "semantic_answer": "generated",
        "serialized_answer": "generated",
        "confidence": 0.97,
        "reasoning": "generated by test engine",
    }
    result.update(overrides)
    return result


# -------------------------------------------------------- stored → type match


def test_select_matches_option_label(fresh_db):
    store_answer(fresh_db, "How did you hear about this job?", "LinkedIn")
    fill = resolve_field(
        fresh_db,
        field(
            FieldKind.SELECT,
            "How did you hear about this job?",
            options=[("linkedin", "LinkedIn"), ("referral", "Referral")],
        ),
        "ai",
    )
    assert fill.filled is True
    assert fill.resolution["semantic_answer"] == "LinkedIn"
    assert fill.source == "manual"
    assert fill.confidence == 1.0
    assert fill.resolution["typed_value"] == "linkedin"  # option id


def test_select_matches_option_value_directly(fresh_db):
    """A stored answer equal to the option value (not label) still matches."""
    store_answer(fresh_db, "Visa status", "us")
    fill = resolve_field(
        fresh_db,
        field(
            FieldKind.SELECT,
            "Visa status",
            options=[("us", "US Citizen"), ("h1b", "H1B / Transfer")],
        ),
        "ai",
    )
    assert fill.filled is True
    assert fill.resolution["semantic_answer"] == "us"


def test_select_unmatched_answer_not_filled(fresh_db):
    store_answer(fresh_db, "How did you hear about this job?", "Narnia")
    fill = resolve_field(
        fresh_db,
        field(
            FieldKind.SELECT,
            "How did you hear about this job?",
            options=[("linkedin", "LinkedIn")],
        ),
        "ai",
    )
    assert fill.filled is False
    assert "no type match" in fill.reason


def test_radio_matches_value(fresh_db):
    store_answer(fresh_db, "Authorization", "Yes, I am legally authorized")
    fill = resolve_field(
        fresh_db,
        field(
            FieldKind.RADIO,
            "Authorization",
            options=[("yes", "Yes, I am legally authorized"), ("no", "No")],
        ),
        "ai",
    )
    assert fill.filled is True
    assert fill.resolution["semantic_answer"] == "Yes, I am legally authorized"


def test_date_normalizes_to_iso(fresh_db):
    store_answer(fresh_db, "Earliest start date", "06/15/2024")
    fill = resolve_field(
        fresh_db, field(FieldKind.DATE, "Earliest start date"), "ai"
    )
    assert fill.filled is True
    assert fill.resolution["semantic_answer"] == "06/15/2024"


def test_date_iso_passthrough_and_invalid(fresh_db):
    store_answer(fresh_db, "Start date A", "2024-06-15")
    assert resolve_field(fresh_db, field(FieldKind.DATE, "Start date A"), "ai").filled
    store_answer(fresh_db, "Start date B", "not a date")
    assert (
        resolve_field(fresh_db, field(FieldKind.DATE, "Start date B"), "ai").filled
        is False
    )


def test_checkbox_truthy_falsy(fresh_db):
    store_answer(fresh_db, "Agree to terms", "yes")
    yes = resolve_field(fresh_db, field(FieldKind.CHECKBOX, "Agree to terms"), "ai")
    assert yes.filled is True
    assert yes.resolution["semantic_answer"] == "yes"

    store_answer(fresh_db, "Agree to terms 2", "No")
    no = resolve_field(fresh_db, field(FieldKind.CHECKBOX, "Agree to terms 2"), "ai")
    assert no.filled is True
    assert no.resolution["semantic_answer"] == "No"


def test_number_leading_numeric(fresh_db):
    store_answer(fresh_db, "Years of experience", "5 years")
    fill = resolve_field(fresh_db, field(FieldKind.NUMBER, "Years of experience"), "ai")
    assert fill.filled is True
    assert fill.resolution["semantic_answer"] == "5 years"

    store_answer(fresh_db, "Years of experience 2", "abc")
    assert (
        resolve_field(fresh_db, field(FieldKind.NUMBER, "Years of experience 2"), "ai")
        .filled
        is False
    )


def test_free_text_passthrough(fresh_db):
    for kind, label in (
        (FieldKind.TEXT, "LinkedIn Profile"),
        (FieldKind.EMAIL, "Email"),
        (FieldKind.PHONE, "Phone"),
        (FieldKind.URL, "Website"),
        (FieldKind.TEXTAREA, "Cover letter"),
    ):
        store_answer(fresh_db, label, "value-for-" + kind.value)
        fill = resolve_field(fresh_db, field(kind, label), "ai")
        assert fill.filled is True, kind
        assert fill.resolution["semantic_answer"] == "value-for-" + kind.value


def test_upload_never_auto_filled(fresh_db):
    store_answer(fresh_db, "Resume/CV", "resume.pdf")
    fill = resolve_field(fresh_db, field(FieldKind.UPLOAD, "Resume/CV"), "ai")
    assert fill.filled is False
    assert "checkpoint" in fill.reason


def test_sensitive_never_auto_filled(fresh_db):
    store_answer(fresh_db, "Date of birth", "1990-01-01")
    fill = resolve_field(
        fresh_db,
        field(FieldKind.DATE, "Date of birth"),
        "ai",
        sensitive=True,
    )
    assert fill.filled is False
    assert "never auto-fill" in fill.reason
    assert fill.resolution["semantic_answer"] == "1990-01-01"  # suggestion staged


def test_unknown_field_not_filled(fresh_db):
    """No stored answer, no deterministic hit, engine abstains → no fill."""
    ctx = ResolveContext(
        conn=fresh_db,
        profile={},
        hybrid_resolver=lambda q, p: {
            "status": "manual_review",
            "source": "llm",
            "semantic_answer": None,
            "serialized_answer": None,
            "confidence": None,
            "reasoning": "abstain",
        },
        cache={},
    )
    fill = resolve_field(
        fresh_db, field(FieldKind.TEXT, "Cosmic question"), "ai", context=ctx
    )
    assert fill.filled is False
    assert fill.confidence is None


def test_deterministic_engine_fill(fresh_db):
    ctx = ResolveContext(
        conn=fresh_db,
        profile={},
        hybrid_resolver=lambda q, p: resolve_hybrid(
            source="deterministic", semantic_answer="San Francisco"
        ),
        cache={},
    )
    fill = resolve_field(
        fresh_db,
        field(
            FieldKind.SELECT,
            "Location",
            options=[("sf", "San Francisco"), ("nyc", "New York")],
        ),
        "ai",
        context=ctx,
    )
    assert fill.filled is True
    assert fill.source == AnswerSource.DETERMINISTIC.value
    assert fill.resolution["semantic_answer"] == "San Francisco"


def test_llm_confidence_passthrough(fresh_db):
    ctx = ResolveContext(
        conn=fresh_db,
        profile={},
        hybrid_resolver=lambda q, p: resolve_hybrid(confidence=0.85),
        cache={},
    )
    fill = resolve_field(fresh_db, field(FieldKind.TEXT, "Intro"), "ai", context=ctx)
    assert fill.filled is True
    assert fill.confidence == 0.85
    assert fill.source == AnswerSource.LLM.value
    assert "generated" in fill.reason


def test_resolve_fields_batch(fresh_db):
    store_answer(fresh_db, "Email", "a@b.com")
    store_answer(fresh_db, "How did you hear", "LinkedIn")
    fills = resolve_fields(
        fresh_db,
        [
            field(FieldKind.EMAIL, "Email", field_id="e"),
            field(
                FieldKind.SELECT,
                "How did you hear",
                options=[("linkedin", "LinkedIn")],
                field_id="s",
            ),
        ],
        "ai",
    )
    assert [f.field_id for f in fills] == ["e", "s"]
    assert all(f.filled for f in fills)


def test_resolve_fields_sensitive_set(fresh_db):
    store_answer(fresh_db, "Email", "a@b.com")
    store_answer(fresh_db, "Address", "123 Main St")
    fills = resolve_fields(
        fresh_db,
        [
            field(FieldKind.EMAIL, "Email", field_id="e"),
            field(FieldKind.TEXT, "Address", field_id="a"),
        ],
        "ai",
        sensitive={"a"},
    )
    assert fills[0].filled is True
    assert fills[1].filled is False
    assert "never auto-fill" in fills[1].reason


def test_field_fill_to_dict_shape(fresh_db):
    store_answer(fresh_db, "How did you hear about this job?", "LinkedIn")
    data = resolve_field(
        fresh_db,
        field(FieldKind.SELECT, "How did you hear about this job?"),
        "ai",
    ).to_dict()
    assert set(data) == {
        "field_id",
        "resolution",
        "filled",
        "confidence",
        "source",
        "reason",
        "fingerprint",
        "write_status",
    }
    assert set(data["resolution"]) == {
        "question_fp",
        "source",
        "semantic_answer",
        "serialized_answer",
        "confidence",
        "status",
        "reasoning",
        "typed_value",
    }


def test_fill_summary_breakdown(fresh_db):
    """D-034 §8: the operational report splits fills by source and reports
    confidence + completion."""
    from src.copilot.browser.resolver import fill_summary

    fills = [
        _profile_fill("p0", 1.0),
        _profile_fill("p1", 1.0),
        _manual_fill("p2"),
        _unresolved_fill("p3"),
    ]
    summary = fill_summary(fills)
    assert summary["application_fields"] == 4
    assert summary["profile_filled"] == 2
    assert summary["human_required"] == 2  # manual + unresolved
    assert summary["filled"] == 2
    # average over ALL fills incl. staged: (1.0 + 1.0 + 0.91 + 0.0) / 4
    assert summary["average_confidence"] == round((1.0 + 1.0 + 0.91 + 0.0) / 4, 4)
    assert summary["completion"] == 50.0


def _profile_fill(fid: str, conf: float):
    from src.copilot.browser.resolver import FieldFill

    return FieldFill(
        field_id=fid,
        resolution={},
        filled=True,
        confidence=conf,
        source="profile",
        reason="deterministic",
        fingerprint="CandidateIdentity.Email",
    )


def _manual_fill(fid: str):
    from src.copilot.browser.resolver import FieldFill

    return FieldFill(
        field_id=fid,
        resolution={},
        filled=False,
        confidence=0.91,
        source="stored",
        reason="staged",
        fingerprint="UNKNOWN",
    )


def _unresolved_fill(fid: str):
    from src.copilot.browser.resolver import FieldFill

    return FieldFill(
        field_id=fid,
        resolution={},
        filled=False,
        confidence=0.0,
        source="deterministic",
        reason="no profile value",
        fingerprint="Employment.VisaStatus",
    )
