from pathlib import Path
from src.audit.markdown_builder import MarkdownBuilder

def generate_summary_report(output_dir: Path):
    mb = MarkdownBuilder("Pipeline Audit Summary")
    mb.add_paragraph("This summary was automatically generated by the Pipeline Intelligence & Explainability Framework.")
    
    mb.add_heading("Generated Reports")
    rows = [
        ["pipeline.md", "Pipeline stages and architecture"],
        ["filters.md", "Complete inventory of all job filters and rejection criteria"],
        ["ai.md", "AI integration points, models, and prompts"],
        ["routing.md", "Job application routing and strategy"],
        ["state.md", "Database schemas and state machine rules"],
        ["config.md", "All configuration values and environment variables"],
        ["cache.md", "Cache configurations and TTLs"],
        ["performance.md", "Metrics tracking and instrumentation"],
        ["architecture.md", "Module dependency graph"],
    ]
    mb.add_table(["Report", "Description"], rows)
    
    mb.add_alert("TIP", "Use `cw audit explain <job_id>` to trace exactly what happened to a specific job.")
    
    output_path = output_dir / "summary.md"
    output_path.write_text(mb.build(), encoding="utf-8")
    return output_path
