"""Extension pairing + bearer token auth (CP-0-04).

Loopback-only, token + Origin validation. Token generated by explicit
pairing and stored at data/copilot_ext_token.json (mode 0600). Never logged.
"""
from __future__ import annotations

import json
import os
import secrets
from datetime import datetime, timezone
from pathlib import Path

import hmac


def _token_path() -> Path:
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / "data").is_dir():
            return parent / "data" / "copilot_ext_token.json"
    return Path(os.getcwd()) / "data" / "copilot_ext_token.json"


def pair() -> str:
    """Generate (or rotate) a pairing token. Returns the token ONCE."""
    token = secrets.token_urlsafe(32)
    path = _token_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(
            {
                "token": token,
                "created_at": datetime.now(timezone.utc).isoformat(),
            }
        ),
        encoding="utf-8",
    )
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass
    return token


def current_token() -> str | None:
    path = _token_path()
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data.get("token")
    except (json.JSONDecodeError, OSError):
        return None


def verify(token: str | None) -> bool:
    expected = current_token()
    if not expected or not token:
        return False
    return hmac.compare_digest(expected, token)
