"""
Canonical candidate evidence store.

Purpose
-------
This file is the factual and policy grounding source for:

    deterministic questionnaire resolution
    LLM questionnaire fallback
    recruiter-question answering
    resume tailoring
    interview story preparation
    application automation

Evidence classes
----------------

verified:
    Directly supported by resume, certification, implemented projects,
    repository history, or known hands-on implementation.

positionable:
    Defensible capability inference from implemented adjacent systems.
    The candidate may answer capability questions positively, but the
    system must not invent employer deployment details, customer metrics,
    dates, scale, or production impact.

approved_answers:
    Explicit application-answer policy.

unsupported:
    Claims that must not be invented or inferred.

sensitive:
    Personal data that must never be generated by an LLM.
"""

CANDIDATE_EVIDENCE = {
    # ==========================================================================
    # Identity / professional positioning
    # ==========================================================================
    "professional_profile": {
        "current_positioning": (
            "Applied AI Engineer and Senior Software Engineer focused on "
            "Generative AI, RAG, agentic systems, AI orchestration, backend "
            "services, and enterprise workflow automation."
        ),
        "total_software_experience_years": 5,
        "current_location": "Pune",
        "preferred_location": "Pune",
        "notice_period_days": 30,
        "current_ctc_lpa": 16,
        "expected_ctc_lpa": 26,
    },
    # ==========================================================================
    # Certifications
    # ==========================================================================
    "certifications": {
        "verified": [
            {
                "name": "Microsoft Certified: Azure AI Engineer Associate",
                "exam": "AI-102",
                "status": "passed",
            },
        ],
    },
    # ==========================================================================
    # Core capability evidence
    # ==========================================================================
    "capabilities": {
        # ----------------------------------------------------------------------
        # Generative AI
        # ----------------------------------------------------------------------
        "generative_ai": {
            "status": "verified",
            "years_policy": 3,
            "level": "hands_on",
            "evidence": [
                "Built multiple Generative AI application projects.",
                "Implemented LLM-integrated workflows.",
                "Implemented structured-output workflows.",
                "Implemented bounded LLM usage inside deterministic systems.",
                "Implemented provider abstraction for local and cloud LLM backends.",
                "Worked with Azure OpenAI integrations.",
                "Worked with local LLM inference through Ollama and oMLX.",
            ],
            "safe_capability_answers": [
                "Have you worked on Generative AI applications?",
                "Do you have hands-on GenAI experience?",
                "Have you integrated LLMs into applications?",
                "Have you built LLM-powered workflows?",
            ],
        },
        # ----------------------------------------------------------------------
        # RAG
        # ----------------------------------------------------------------------
        "rag": {
            "status": "verified",
            "years_policy": 3,
            "level": "advanced_hands_on",
            "evidence": [
                "Built RAG systems for technical and API documentation.",
                "Implemented dense vector retrieval using FAISS.",
                "Implemented BM25 sparse retrieval.",
                "Implemented hybrid dense and sparse retrieval.",
                "Implemented cross-encoder reranking.",
                "Implemented parent-child retrieval.",
                "Implemented multi-query retrieval.",
                "Implemented contextual compression.",
                "Implemented metadata-aware filtering.",
                "Implemented source-aware ingestion pipelines.",
                "Implemented retrieval evaluation using Recall@K.",
                "Implemented grounding and relevance evaluation.",
                "Worked with Azure AI Search.",
                "Worked with semantic search and semantic ranking concepts.",
            ],
            "safe_capability_answers": [
                "Do you have experience with RAG?",
                "Do you have experience with context engineering?",
                "Have you built advanced RAG pipelines?",
                "Have you worked with hybrid retrieval?",
                "Have you implemented reranking?",
                "Have you worked with vector databases?",
            ],
        },
        # ----------------------------------------------------------------------
        # Agentic AI
        # ----------------------------------------------------------------------
        "agentic_ai": {
            "status": "verified",
            "years_policy": 3,
            "level": "hands_on",
            "evidence": [
                "Built an AI Customer Support Copilot with orchestrator-controlled execution.",
                "Built an Agentic Loan Underwriting System.",
                "Implemented specialized Intake, Risk, and Compliance processing stages.",
                "Implemented tool calling.",
                "Implemented planning and plan validation.",
                "Implemented tool selection and execution.",
                "Implemented multi-intent workflow handling.",
                "Implemented confidence-aware validation.",
                "Implemented deterministic policy boundaries around probabilistic AI components.",
                "Evaluated LangChain, LangGraph, and AutoGen orchestration approaches.",
            ],
            "safe_capability_answers": [
                "Have you built AI agents?",
                "Do you have experience with agentic AI?",
                "Have you implemented tool-calling workflows?",
                "Have you built multi-step AI workflows?",
                "Have you implemented planner-executor architecture?",
            ],
        },
        # ----------------------------------------------------------------------
        # Rule engines / decision systems
        # ----------------------------------------------------------------------
        "rule_engines_and_decision_logic": {
            "status": "positionable",
            "level": "hands_on_adjacent_and_equivalent",
            "evidence": [
                "Implemented deterministic intent routing rules.",
                "Implemented planner validation.",
                "Implemented slot validation before tool execution.",
                "Implemented deterministic policy checks in underwriting workflows.",
                "Separated deterministic risk policies from probabilistic extraction.",
                "Implemented confidence-aware decision handling.",
                "Implemented fallback routing.",
                "Implemented validation checkpoints before downstream actions.",
                "Implemented response validation policies.",
                "Implemented escalation decisions.",
                "Implemented deterministic and LLM hybrid routing.",
            ],
            "allowed_positioning": (
                "Yes. I have implemented deterministic business-rule, validation, "
                "routing, policy-check, and heuristic decision layers within "
                "workflow orchestration and AI-assisted systems."
            ),
            "prohibited_expansion": [
                "Do not claim use of a named commercial rule-engine product unless verified.",
                "Do not claim ownership of an enterprise-wide rule platform.",
                "Do not invent production transaction volumes.",
            ],
        },
        # ----------------------------------------------------------------------
        # LLM orchestration
        # ----------------------------------------------------------------------
        "llm_orchestration": {
            "status": "verified",
            "level": "advanced_hands_on",
            "evidence": [
                "Implemented custom Python orchestration.",
                "Implemented intent classification.",
                "Implemented routing.",
                "Implemented planning.",
                "Implemented plan validation.",
                "Implemented executor components.",
                "Implemented tool registry and tool selection.",
                "Implemented structured outputs.",
                "Implemented response validation.",
                "Implemented fallback mechanisms.",
                "Implemented bounded LLM usage.",
                "Compared custom orchestration with framework adapters.",
            ],
        },
        # ----------------------------------------------------------------------
        # FastAPI
        # ----------------------------------------------------------------------
        "fastapi": {
            "status": "verified",
            "years_policy": 3,
            "level": "hands_on",
            "evidence": [
                "Implemented FastAPI services for AI systems.",
                "Implemented API layers around RAG and AI workflows.",
                "Implemented FastAPI services in the Agentic Loan Underwriting System.",
                "Containerized Python and FastAPI services.",
                "Worked with asynchronous processing architectures.",
                "Implemented streaming response workflows.",
            ],
            "safe_capability_answers": [
                "Have you built FastAPI APIs?",
                "Have you built AI microservices?",
                "Have you built model-serving integration APIs?",
            ],
        },
        # ----------------------------------------------------------------------
        # Local model inference and serving
        # ----------------------------------------------------------------------
        "local_llm_inference": {
            "status": "verified",
            "level": "hands_on",
            "evidence": [
                "Used Ollama for local model inference.",
                "Used oMLX for local MLX model serving.",
                "Integrated OpenAI-compatible local inference APIs.",
                "Configured multiple local Qwen model variants.",
                "Implemented configurable local and Azure LLM provider switching.",
            ],
        },
        "ollama": {
            "status": "verified",
            "level": "hands_on",
            "answer": "Yes",
            "evidence": [
                "Used Ollama for local LLM inference.",
                "Integrated Ollama-backed generation into AI application workflows.",
                "Tested multiple local instruction and reasoning models.",
            ],
        },
        "omlx": {
            "status": "verified",
            "level": "hands_on",
            "answer": "Yes",
            "evidence": [
                "Runs oMLX locally on Apple Silicon.",
                "Uses OpenAI-compatible chat completion APIs.",
                "Configured memory guard and paged SSD caching.",
                "Integrated qwen3.5-4b as an application-question resolver model.",
            ],
        },
        "vllm": {
            "status": "unsupported",
            "answer_policy": "manual_review",
            "reason": (
                "No direct implementation evidence currently establishes hands-on "
                "vLLM usage. Do not convert Ollama or oMLX experience into a vLLM claim."
            ),
        },
        # ----------------------------------------------------------------------
        # LLM deployment
        # ----------------------------------------------------------------------
        "llm_deployment": {
            "status": "positionable",
            "level": "application_integration_and_serving",
            "evidence": [
                "Integrated local inference backends.",
                "Integrated Azure OpenAI backends.",
                "Implemented provider-agnostic LLM interfaces.",
                "Containerized AI application services.",
                "Built API-driven AI service architectures.",
            ],
            "allowed_positioning": (
                "Yes. I have integrated and served LLM-backed application workflows "
                "using local inference runtimes and Azure OpenAI-backed services."
            ),
            "prohibited_expansion": [
                "Do not claim training foundation models.",
                "Do not claim managing a large GPU inference cluster.",
                "Do not claim vLLM deployment unless separately verified.",
            ],
        },
        # ----------------------------------------------------------------------
        # Azure AI
        # ----------------------------------------------------------------------
        "azure_ai": {
            "status": "verified",
            "years_policy": 2,
            "level": "hands_on_and_certified",
            "evidence": [
                "Microsoft Certified Azure AI Engineer Associate.",
                "Worked with Azure OpenAI.",
                "Worked with Azure AI Search.",
                "Worked with Microsoft Foundry concepts and services.",
                "Studied and implemented Azure AI application architecture.",
                "Built provider abstractions supporting Azure-backed AI services.",
            ],
        },
        # ----------------------------------------------------------------------
        # LangChain
        # ----------------------------------------------------------------------
        "langchain": {
            "status": "verified",
            "years_policy": 2,
            "level": "hands_on",
            "evidence": [
                "Built LangChain adapters around core AI application logic.",
                "Compared LangChain orchestration with custom core architecture.",
                "Used LangChain concepts for LLM and retrieval workflows.",
            ],
        },
        # ----------------------------------------------------------------------
        # LangGraph
        # ----------------------------------------------------------------------
        "langgraph": {
            "status": "verified",
            "years_policy": 2,
            "level": "hands_on",
            "evidence": [
                "Implemented LangGraph adapter experiments.",
                "Compared graph orchestration with custom deterministic orchestration.",
                "Worked with stateful multi-step workflow concepts.",
            ],
        },
        # ----------------------------------------------------------------------
        # AutoGen
        # ----------------------------------------------------------------------
        "autogen": {
            "status": "verified",
            "level": "hands_on_evaluation",
            "evidence": [
                "Implemented AutoGen adapter experiments.",
                "Compared AutoGen execution characteristics with custom core architecture.",
            ],
        },
        # ----------------------------------------------------------------------
        # Semantic Kernel
        # ----------------------------------------------------------------------
        "semantic_kernel": {
            "status": "verified_resume_claim",
            "level": "working_knowledge",
            "evidence": [
                "Listed in current technical skills.",
                "Included in Azure-centric AI engineering preparation.",
            ],
            "answer_guidance": (
                "Answer capability questions conservatively. Do not describe major "
                "production Semantic Kernel deployments without project-specific evidence."
            ),
        },
        # ----------------------------------------------------------------------
        # Embeddings / vector search
        # ----------------------------------------------------------------------
        "vector_search": {
            "status": "verified",
            "years_policy": 2,
            "level": "advanced_hands_on",
            "evidence": [
                "Implemented FAISS dense retrieval.",
                "Implemented embedding generation and indexing.",
                "Implemented semantic search workflows.",
                "Implemented hybrid retrieval.",
                "Worked with Azure AI Search.",
                "Worked with Chroma in experimentation and development contexts.",
            ],
        },
        # ----------------------------------------------------------------------
        # Evaluation
        # ----------------------------------------------------------------------
        "ai_evaluation": {
            "status": "verified",
            "years_policy": 2,
            "level": "hands_on",
            "evidence": [
                "Built evaluation query suites.",
                "Implemented retrieval evaluation using Recall@K.",
                "Implemented grounding and relevance evaluation.",
                "Implemented workflow-level evaluation.",
                "Tested intent classification and routing behavior.",
                "Evaluated orchestration framework variants.",
                "Tracked latency and execution behavior.",
            ],
        },
        # ----------------------------------------------------------------------
        # Prompt engineering
        # ----------------------------------------------------------------------
        "prompt_engineering": {
            "status": "verified",
            "years_policy": 3,
            "level": "hands_on",
            "evidence": [
                "Designed structured prompts for LLM workflows.",
                "Used structured outputs.",
                "Implemented schema validation.",
                "Implemented bounded prompts for classification and resolution.",
                "Implemented prompt-driven extraction with deterministic validation.",
            ],
        },
        # ----------------------------------------------------------------------
        # Context engineering
        # ----------------------------------------------------------------------
        "context_engineering": {
            "status": "verified",
            "level": "advanced_hands_on",
            "evidence": [
                "Implemented retrieval context selection.",
                "Implemented reranking.",
                "Implemented contextual compression.",
                "Implemented parent-child retrieval.",
                "Implemented metadata filtering.",
                "Implemented grounded prompt construction.",
                "Implemented source-aware ingestion.",
            ],
        },
        # ----------------------------------------------------------------------
        # Python
        # ----------------------------------------------------------------------
        "python": {
            "status": "verified",
            "years_policy": 3,
            "level": "hands_on",
            "evidence": [
                "Built AI orchestration services in Python.",
                "Built retrieval systems in Python.",
                "Built FastAPI applications.",
                "Built evaluation workflows.",
                "Built asynchronous AI workflow components.",
            ],
        },
        # ----------------------------------------------------------------------
        # Angular
        # ----------------------------------------------------------------------
        "angular": {
            "status": "verified",
            "years_policy": 4,
            "level": "advanced_professional",
            "evidence": [
                "Professional Angular development since 2021.",
                "Worked across Angular enterprise applications.",
                "Worked with RxJS and TypeScript.",
                "Built reusable component architecture.",
                "Worked with routing, state handling, lazy loading, and API integration.",
                "Worked with Angular versions across multiple generations.",
            ],
        },
        # ----------------------------------------------------------------------
        # Node.js
        # ----------------------------------------------------------------------
        "nodejs": {
            "status": "verified",
            "years_policy": 3,
            "level": "professional",
            "evidence": [
                "Built Node.js and Express.js backend services.",
                "Worked with REST APIs.",
                "Worked with authentication and backend integrations.",
                "Built full-stack Angular and Node.js applications.",
            ],
        },
        # ----------------------------------------------------------------------
        # TypeScript
        # ----------------------------------------------------------------------
        "typescript": {
            "status": "verified",
            "years_policy": 4,
            "level": "advanced_professional",
            "evidence": [
                "Used TypeScript extensively in enterprise Angular development.",
            ],
        },
        # ----------------------------------------------------------------------
        # Docker
        # ----------------------------------------------------------------------
        "docker": {
            "status": "verified",
            "level": "hands_on",
            "evidence": [
                "Containerized Python AI services.",
                "Containerized FastAPI services.",
                "Used containerized environments for consistent application deployment.",
            ],
        },
        # ----------------------------------------------------------------------
        # CI/CD
        # ----------------------------------------------------------------------
        "cicd": {
            "status": "verified",
            "level": "hands_on",
            "evidence": [
                "Worked with GitHub Actions.",
                "Worked with CI/CD workflows.",
                "Integrated testing into application delivery workflows.",
            ],
        },
        # ----------------------------------------------------------------------
        # Reliability engineering
        # ----------------------------------------------------------------------
        "reliability_engineering": {
            "status": "verified",
            "level": "hands_on",
            "evidence": [
                "Implemented retries.",
                "Implemented fallback paths.",
                "Implemented circuit breakers.",
                "Implemented rate limiting.",
                "Implemented concurrency controls.",
                "Implemented response validation.",
                "Implemented structured error handling.",
                "Implemented execution tracing.",
                "Implemented metrics.",
                "Implemented semantic caching.",
                "Implemented Redis-backed state.",
            ],
        },
        # ----------------------------------------------------------------------
        # Celery / asynchronous processing
        # ----------------------------------------------------------------------
        "celery": {
            "status": "verified",
            "level": "project_hands_on",
            "evidence": [
                "Implemented Celery-based asynchronous processing in the Agentic Loan Underwriting System.",
            ],
        },
        # ----------------------------------------------------------------------
        # Redis
        # ----------------------------------------------------------------------
        "redis": {
            "status": "verified",
            "level": "project_hands_on",
            "evidence": [
                "Implemented Redis-backed state and caching in AI application architecture.",
            ],
        },
        # ----------------------------------------------------------------------
        # Machine learning
        # ----------------------------------------------------------------------
        "machine_learning": {
            "status": "positionable",
            "years_policy": 3,
            "level": "applied_ai_engineering",
            "evidence": [
                "Uses embedding models.",
                "Uses cross-encoder reranking models.",
                "Uses sentence-transformer models.",
                "Builds AI evaluation pipelines.",
                "Integrates ML and LLM components into applications.",
            ],
            "answer_guidance": (
                "Position as applied ML/AI engineering. Do not claim deep model "
                "training research, novel architecture development, or extensive "
                "classical ML model-development ownership unless specifically supported."
            ),
        },
        # ----------------------------------------------------------------------
        # NLP
        # ----------------------------------------------------------------------
        "nlp": {
            "status": "positionable",
            "years_policy": 2,
            "level": "applied_nlp",
            "evidence": [
                "Built retrieval and semantic search systems.",
                "Worked with embeddings.",
                "Worked with reranking.",
                "Built LLM-based information extraction.",
                "Built contextual response generation systems.",
            ],
        },
        # ----------------------------------------------------------------------
        # MLOps
        # ----------------------------------------------------------------------
        "mlops": {
            "status": "positionable",
            "level": "ai_application_operations",
            "evidence": [
                "Dockerized AI services.",
                "Worked with CI/CD.",
                "Implemented evaluation workflows.",
                "Implemented observability and tracing.",
                "Implemented API deployment patterns.",
                "Worked with Azure AI application deployment concepts.",
            ],
            "answer_guidance": (
                "Position as MLOps for AI application delivery and operations. "
                "Do not claim ownership of large-scale model training pipelines "
                "or feature-store infrastructure without evidence."
            ),
        },
        # ----------------------------------------------------------------------
        # Kubernetes
        # ----------------------------------------------------------------------
        "kubernetes": {
            "status": "working_knowledge",
            "level": "limited",
            "answer_guidance": (
                "Do not claim deep production Kubernetes platform ownership. "
                "Capability answers should distinguish deployment familiarity "
                "from cluster administration expertise."
            ),
        },
        # ----------------------------------------------------------------------
        # Terraform / Bicep
        # ----------------------------------------------------------------------
        "infrastructure_as_code": {
            "status": "working_knowledge",
            "level": "limited",
            "answer_guidance": (
                "Do not claim extensive Terraform or Bicep production ownership "
                "without specific implementation evidence."
            ),
        },
        # ----------------------------------------------------------------------
        # Databricks
        # ----------------------------------------------------------------------
        "databricks": {
            "status": "unsupported",
            "years_policy": 0,
            "answer_policy": "answer_zero_or_no",
        },
        # ----------------------------------------------------------------------
        # .NET
        # ----------------------------------------------------------------------
        "dotnet": {
            "status": "unsupported",
            "years_policy": 0,
            "answer_policy": "answer_zero_or_no",
        },
        # ----------------------------------------------------------------------
        # React Native
        # ----------------------------------------------------------------------
        "react_native": {
            "status": "unsupported",
            "years_policy": 0,
            "published_apps": 0,
        },
        # ----------------------------------------------------------------------
        # Computer Vision
        # ----------------------------------------------------------------------
        "computer_vision": {
            "status": "unsupported",
            "years_policy": 0,
            "answer_policy": "manual_review_or_zero",
        },
    },
    # ==========================================================================
    # Employment evidence
    # ==========================================================================
    "employment": {
        "bajaj_finserv_snapwork": {
            "period": "July 2025 - Present",
            "role": "Senior Software Engineer",
            "verified_resume_claims": [
                "AI-enabled workflow orchestration.",
                "Deterministic business rules.",
                "LLM-assisted workflows.",
                "Contextual validation.",
                "Information interpretation.",
                "Routing.",
                "Structured outputs.",
                "Schema validation.",
                "Confidence-aware handling.",
                "Deterministic verification.",
                "Fallback mechanisms.",
                "API-driven orchestration.",
                "Retries.",
                "Execution tracing.",
                "Validation checkpoints.",
            ],
            "guardrails": [
                "Do not invent exact production transaction volume.",
                "Do not invent model accuracy improvements.",
                "Do not invent financial ROI.",
                "Do not invent customer counts.",
                "Do not claim autonomous loan approval by an LLM.",
            ],
        },
        "cloudbolt": {
            "period": "March 2023 - June 2025",
            "role": "Software Engineer",
            "verified_resume_claims": [
                "AI-assisted knowledge retrieval.",
                "Contextual response workflows.",
                "RAG-oriented pipelines.",
                "Document and knowledge-source processing.",
                "Chunking strategies.",
                "Semantic retrieval.",
                "Contextual filtering.",
                "Grounded response construction.",
                "Query preprocessing.",
                "Metadata-aware filtering.",
                "Context selection.",
                "Retrieval-response quality evaluation.",
                "Enterprise API integration.",
                "Authentication and RBAC integration.",
            ],
            "guardrails": [
                "Do not invent named customer deployments.",
                "Do not invent user counts.",
                "Do not invent revenue impact.",
                "Do not invent latency percentages.",
            ],
        },
        "oerlikon_software_engineer": {
            "period": "May 2021 - March 2023",
            "role": "Software Engineer",
            "verified_resume_claims": [
                "Angular.",
                "RxJS.",
                "TypeScript.",
                "REST API integration.",
                "Reusable component architecture.",
                "Dynamic routing.",
                "Reactive state handling.",
                "Lazy loading.",
                "Validation.",
                "Role-based functionality.",
                "Unit testing.",
            ],
        },
        "oerlikon_business_analyst": {
            "period": "September 2017 - May 2021",
            "role": "Business Analyst",
            "verified_resume_claims": [
                "Digital transformation support.",
                "Process optimization.",
                "KPI analysis.",
                "CRM systems.",
                "Business-process analysis.",
                "Stakeholder coordination.",
                "Requirements analysis.",
                "Process mapping.",
                "Workflow improvement.",
            ],
        },
    },
    # ==========================================================================
    # Project evidence
    # ==========================================================================
    "projects": {
        "ai_customer_support_copilot": {
            "status": "verified_project",
            "evidence": [
                "Orchestrator-controlled routing.",
                "Tool-first execution.",
                "RAG integration.",
                "Structured outputs.",
                "Bounded LLM usage.",
                "Provider-agnostic LLM abstraction.",
                "Local inference support.",
                "Azure OpenAI support.",
                "Intent classification.",
                "Routing.",
                "Planning.",
                "Plan validation.",
                "Tool selection.",
                "Executor components.",
                "Multi-intent workflows.",
                "LangChain adapter.",
                "LangGraph adapter.",
                "AutoGen adapter.",
                "SSE streaming.",
                "Semantic caching.",
                "Redis-backed state.",
                "Retries.",
                "Concurrency controls.",
                "Rate limiting.",
                "Circuit breakers.",
                "Execution tracing.",
                "Metrics.",
                "Response validation.",
                "Evaluation workflows.",
            ],
        },
        "agentic_loan_underwriting_system": {
            "status": "verified_project",
            "evidence": [
                "Deterministic risk policies.",
                "Specialized AI processing stages.",
                "Document intelligence.",
                "Tool calling.",
                "LLM-assisted extraction.",
                "Intake processing.",
                "Risk processing.",
                "Compliance processing.",
                "Asynchronous execution.",
                "Retry handling.",
                "Confidence-aware validation.",
                "Policy checks.",
                "Explainable outputs.",
                "Deterministic-first extraction.",
                "LLM fallback for ambiguous fields.",
                "Consistency validation.",
                "Cross-source verification.",
                "FastAPI.",
                "Celery.",
                "Decision traces.",
                "Evaluation workflows.",
                "Failure handling.",
            ],
        },
        "rag_api_assistant": {
            "status": "verified_project",
            "evidence": [
                "Hybrid retrieval.",
                "FAISS dense retrieval.",
                "BM25 sparse retrieval.",
                "Multi-query retrieval.",
                "Cross-encoder reranking.",
                "Contextual compression.",
                "Parent-child retrieval.",
                "HTML ingestion.",
                "Markdown ingestion.",
                "OpenAPI ingestion.",
                "PDF ingestion.",
                "Source-aware parsing.",
                "Chunking.",
                "Metadata handling.",
                "Embedding generation.",
                "Indexing.",
                "Recall@K evaluation.",
                "Retrieval tracing.",
                "Grounding evaluation.",
                "Relevance evaluation.",
                "Semantic caching.",
                "Streaming responses.",
                "Latency metrics.",
            ],
        },
    },
    # ==========================================================================
    # Approved application-answer policy
    # ==========================================================================
    "approved_answers": {
        "experience_years": {
            "generative_ai": 3,
            "rag": 3,
            "agentic_ai": 3,
            "llm": 3,
            "python": 3,
            "machine_learning": 3,
            "angular": 4,
            "typescript": 4,
            "nodejs": 3,
            "langchain": 2,
            "langgraph": 2,
            "vector_databases": 2,
            "nlp": 2,
            "prompt_engineering": 3,
            "ai_evaluation": 2,
            "azure": 2,
            "cloud": 3,
            "api_development": 3,
            "sql": 1,
            "databricks": 0,
            "dotnet": 0,
            "computer_vision": 0,
        },
        "capability_answers": {
            "rag": "Yes",
            "context_engineering": "Yes",
            "fastapi": "Yes",
            "ai_microservices": "Yes",
            "agentic_ai": "Yes",
            "tool_calling": "Yes",
            "structured_outputs": "Yes",
            "hybrid_retrieval": "Yes",
            "reranking": "Yes",
            "ollama": "Yes",
            "local_llm_inference": "Yes",
            "docker": "Yes",
            "ci_cd": "Yes",
            "rule_based_decision_logic": "Yes",
            "llm_orchestration": "Yes",
            "azure_openai": "Yes",
            "azure_ai_search": "Yes",
        },
        "employment_preferences": {
            "remote_work": "Yes",
            "work_from_office": "Yes",
            "relocation": "Yes",
            "contract_to_hire": "Yes",
            "one_year_contract": "Yes",
            "interview_availability": "Yes",
            "offer_in_hand": "No",
            "career_break": "No",
        },
        "job_change_reason": (
            "Seeking a production GenAI, RAG and agentic AI engineering role "
            "with greater technical ownership."
        ),
    },
    # ==========================================================================
    # Claims requiring careful positioning
    # ==========================================================================
    "positionable_claims": {
        "rule_engine_experience": {
            "allowed": True,
            "basis": (
                "Implemented deterministic business rules, policy checks, routing, "
                "validation, confidence thresholds, fallbacks, and decision logic."
            ),
            "safe_answer": (
                "Yes. I have implemented rule-driven decision logic, validation "
                "policies, routing rules, heuristic checks, and deterministic "
                "control layers within workflow and AI orchestration systems."
            ),
        },
        "model_serving": {
            "allowed": True,
            "basis": (
                "Implemented local inference integrations, OpenAI-compatible APIs, "
                "FastAPI AI services, Ollama integration, oMLX integration, and "
                "Azure OpenAI provider integrations."
            ),
            "safe_answer": (
                "Yes. I have built API-driven LLM application services and integrated "
                "both local inference runtimes and Azure OpenAI-backed providers."
            ),
        },
        "mlops": {
            "allowed": True,
            "basis": (
                "Docker, CI/CD, API deployment, evaluation, tracing, observability, "
                "retries, caching, and Azure AI application deployment work."
            ),
            "safe_answer": (
                "Yes, primarily on the AI application delivery side: containerization, "
                "CI/CD, API deployment, evaluation, observability, tracing, and "
                "runtime reliability controls."
            ),
        },
        "production_ai": {
            "allowed": True,
            "basis": (
                "Production-oriented application engineering, enterprise workflow "
                "integration, reliability controls, and deployment architecture."
            ),
            "safe_answer": (
                "I have built production-oriented AI application architectures with "
                "validation, fallbacks, observability, retries, caching, evaluation, "
                "and deterministic control boundaries."
            ),
        },
    },
    # ==========================================================================
    # Unsupported claims
    # ==========================================================================
    "unsupported_claims": {
        "never_invent": [
            "Exact production user count unless explicitly stored as verified evidence.",
            "Exact ROI percentage.",
            "Exact cost-reduction percentage.",
            "Exact latency-improvement percentage.",
            "Exact revenue impact.",
            "Exact number of production requests per day.",
            "Exact model accuracy improvement.",
            "Exact production deployment duration unless verified.",
            "Named customer deployments not present in evidence.",
            "Foundation-model training.",
            "Large-scale GPU cluster management.",
            "Deep Kubernetes administration.",
            "Production vLLM usage.",
            "Databricks professional experience.",
            ".NET professional experience.",
            "Published React Native applications.",
            "Computer Vision professional experience.",
            "Fine-tuning or LoRA implementation unless separately verified.",
            "Terraform production ownership unless separately verified.",
            "Bicep production ownership unless separately verified.",
        ],
    },
    # ==========================================================================
    # Sensitive information policy
    # ==========================================================================
    "sensitive_information": {
        "always_manual_review": [
            "PAN number",
            "Aadhaar number",
            "passport number",
            "date of birth",
            "full residential address",
            "bank account information",
            "tax identifiers",
            "government identification numbers",
        ],
        "policy": (
            "The LLM must never generate, infer, fabricate, retrieve from unrelated "
            "context, or auto-submit sensitive personal identifiers."
        ),
    },
    # ==========================================================================
    # LLM resolver policy
    # ==========================================================================
    "llm_policy": {
        "answer_yes_when": [
            "Direct verified evidence supports the capability.",
            "Multiple project evidence items directly implement the capability.",
            "A positionable claim has an explicit allowed positioning policy.",
        ],
        "manual_review_when": [
            "The question requests sensitive personal information.",
            "The question requests exact production metrics without verified evidence.",
            "The question requests exact dates or durations without verified evidence.",
            "The question names a specific technology with no direct or approved evidence.",
            "Answering requires inventing employer-specific implementation details.",
            "Answering requires converting general experience years into deployment duration.",
        ],
        "reasoning_rules": [
            "Use only retrieved evidence.",
            "Do not infer exact metrics from general capability evidence.",
            "Do not infer production duration from years of experience.",
            "Do not convert adjacent tools into direct hands-on claims.",
            "Do not invent employer-specific incidents.",
            "Do not invent customer names.",
            "Do not invent deployment scale.",
            "Prefer concise recruiter-compatible answers.",
            "Abstain when evidence is insufficient.",
        ],
    },
}
